### ISSUE TITLE
Pull in Weather Data

### ISSUE THREAD

**Issue by s-etty** [s-etty/mhm-scraper#2]
Will need to pull in weather data from somewhere. We should look at who has good API's.

**Comment by s-etty** [comment]
@jackie-kinsler Do you think we need any more weather data? I feel like that's enough. I can get snow depth from the meadows page too. Should we close this?

**Comment by jackie-kinsler** [comment]
I think what we have is enough. IDK if snow depth is going to make much of a difference after December.
